# Build Workflow - Tests and builds Docker images on master push
# Triggered on master branch pushes (excluding tags)

when:
  event: push
  branch: master

steps:
  - name: build-test
    image: node:20-alpine
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build

  - name: build-dockerhub
    image: woodpeckerci/plugin-docker-buildx:latest
    depends_on:
      - build-test
    settings:
      repo:
        from_secret: docker_repo
      registry: docker.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - prod-${CI_COMMIT_SHA:0:7}
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

  - name: build-ghcr
    image: woodpeckerci/plugin-docker-buildx:latest
    depends_on:
      - build-test
    settings:
      repo:
        from_secret: ghcr_repo
      registry: ghcr.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - prod-${CI_COMMIT_SHA:0:7}
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
