# CI Workflow - Tests and linting on pull requests
# Triggered only on pull_request events
# This workflow runs independently and reports its own status

steps:
  ci-lint-and-test:
    image: node:20-alpine
    when:
      - event: pull_request
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      # Use corepack to enable pnpm
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      # Install dependencies
      - pnpm install --frozen-lockfile
      # Run checks
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
