# CI Pipeline - Tests and Checks on Pull Requests
# Based on official Woodpecker examples (woodpecker-ci/woodpecker, LemmyNet/lemmy-js-client)

steps:
  ci-test:
    image: node:20-alpine
    when:
      event: pull_request
      branch: master
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      # Use corepack to enable pnpm (official Woodpecker approach)
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      # Install dependencies
      - pnpm install --frozen-lockfile
      # Run checks
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
