# CI Pipeline - Tests and Checks on Pull Requests
# Runs on pull requests to master branch

steps:
  ci-test:
    image: node:20-alpine
    when:
      event: pull_request
      branch: master
    environment:
      PNPM_HOME: /root/.pnpm
      PATH: ${PNPM_HOME}:$PATH
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -g pnpm@10
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
