# CI Workflow - Tests and linting on pull requests
# Triggered only on pull_request events

steps:
  - name: ci-lint-and-test
    image: node:20-alpine
    when:
      event: pull_request
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
