# CI Pipeline - Tests and Checks
# Based on official Woodpecker examples (woodpecker-ci/woodpecker, LemmyNet/lemmy-js-client)
# Avoids duplicate testing: tests on PR creation OR direct push to master, not both

steps:
  ci-test:
    image: node:20-alpine
    when:
      # Test all pull requests
      - event: pull_request
      # Also test direct pushes to master (but not feature branch pushes)
      - event: push
        branch: master
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      # Use corepack to enable pnpm (official Woodpecker approach)
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      # Install dependencies
      - pnpm install --frozen-lockfile
      # Run checks
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
