# CI Pipeline - Tests and Checks
# Based on official Woodpecker examples (woodpecker-ci/woodpecker, LemmyNet/lemmy-js-client)
# Avoids duplicate testing: tests on PR creation OR direct push to master, not both
# Custom clone step prevents wasteful clones on feature branch pushes

skip_clone: true  # Disable automatic clone, we define a custom one with conditions

steps:
  # Custom clone step - only runs on pull requests
  clone:
    image: woodpeckerci/plugin-git:latest
    when:
      - event: pull_request

  ci-test:
    image: node:20-alpine
    when:
      # Test all pull requests only
      - event: pull_request
    depends_on:
      - clone
    environment:
      SKIP_ENV_VALIDATION: "true"
    commands:
      # Use corepack to enable pnpm (official Woodpecker approach)
      - npm install -f -g corepack@latest
      - corepack enable pnpm
      # Install dependencies
      - pnpm install --frozen-lockfile
      # Run checks
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
