# Deployment Pipeline - Build, Push, and Deploy on master push
# Triggered on direct pushes to master (not on version tags)

variables:
  K8S_NAMESPACE: portfolio
  DEPLOYMENT_NAME: portfolio-nextjs
  CONTAINER_NAME: nextjs

steps:
  # Test
  deploy-test:
    image: node:20-alpine
    when:
      event: push
      branch: master
      exclude_tags: true
    environment:
      PNPM_HOME: /root/.pnpm
      PATH: ${PNPM_HOME}:$PATH
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -g pnpm@10
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build

  # Build and Push Docker Image
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:latest
    when:
      event: push
      branch: master
    settings:
      repo:
        from_secret: docker_repo
      registry: docker.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - main-${CI_COMMIT_SHA:0:7}
        - dev
      build_args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      - deploy-test

  build-and-push-ghcr:
    image: woodpeckerci/plugin-docker-buildx:latest
    when:
      event: push
      branch: master
      exclude_tags: true
    settings:
      repo:
        from_secret: ghcr_repo
      registry: ghcr.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - main-${CI_COMMIT_SHA:0:7}
        - dev
      build_args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      - deploy-test

  # Deploy to Kubernetes
  deploy:
    image: alpine/k8s:latest
    when:
      event: push
      branch: master
      exclude_tags: true
    environment:
      KUBECONFIG: /tmp/kubeconfig
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
    commands:
      - echo "${KUBECONFIG_CONTENT}" | base64 -d > /tmp/kubeconfig
      - IMAGE="ghcr.io/${GHCR_REPO}:main-${CI_COMMIT_SHA:0:7}"
      - echo "Deploying development build: $IMAGE"
      - kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=$IMAGE -n ${K8S_NAMESPACE}
      - kubectl annotate deployment/${DEPLOYMENT_NAME} kubernetes.io/change-cause="Deploy dev build ${CI_COMMIT_SHA:0:7} ($(date '+%Y-%m-%d %H:%M:%S'))" -n ${K8S_NAMESPACE} --overwrite
      - kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE} --timeout=10m
      - kubectl get pods -n ${K8S_NAMESPACE} -l app=portfolio-nextjs -o wide
    depends_on:
      - build-and-push-ghcr
