# Deploy Workflow - Deploys to Kubernetes
# Triggered on master branch pushes after build completes
# Depends on: build workflow

when:
  event: push
  branch: master

steps:
  - name: test-secrets
    image: alpine:latest
    environment:
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
    commands:
      - echo "KUBECONFIG_CONTENT length:" ${#KUBECONFIG_CONTENT}
      - echo "GHCR_REPO value:" "${GHCR_REPO}"
      - echo "CI vars work - SHA:" ${CI_COMMIT_SHA:0:7}

  - name: deploy-k8s
    image: alpine:latest
    depends_on:
      - test-secrets
    environment:
      KUBECONFIG: /tmp/kubeconfig
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
    commands:
      - apk add --no-cache kubectl coreutils
      - echo "${KUBECONFIG_CONTENT}" | base64 -d > /tmp/kubeconfig
      - IMAGE="ghcr.io/${GHCR_REPO}:main-${CI_COMMIT_SHA:0:7}"
      - printf "Deploying development build %s\n" "$IMAGE"
      - kubectl set image deployment/portfolio nextjs=$IMAGE -n portfolio
      - kubectl annotate deployment/portfolio kubernetes.io/change-cause="Deploy dev build ${CI_COMMIT_SHA:0:7} ($(date '+%Y-%m-%d %H:%M:%S'))" -n portfolio --overwrite
      - kubectl rollout status deployment/portfolio -n portfolio --timeout=10m
      - kubectl get pods -n portfolio -l app=portfolio -o wide

depends_on:
  - build
