# Deploy Workflow - Deploys to Kubernetes
# Triggered on master branch pushes after build completes
# Depends on: build workflow

steps:
  - name: deploy-k8s
    image: alpine/k8s:latest
    when:
      event: push
      branch: master
    environment:
      KUBECONFIG: /tmp/kubeconfig
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
      K8S_NAMESPACE: portfolio
      DEPLOYMENT_NAME: portfolio-nextjs
      CONTAINER_NAME: nextjs
    commands:
      - echo "${KUBECONFIG_CONTENT}" | base64 -d > /tmp/kubeconfig
      - IMAGE="ghcr.io/${GHCR_REPO}:main-${CI_COMMIT_SHA:0:7}"
      - printf "Deploying development build %s\n" "$IMAGE"
      - kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=$IMAGE -n ${K8S_NAMESPACE}
      - kubectl annotate deployment/${DEPLOYMENT_NAME} kubernetes.io/change-cause="Deploy dev build ${CI_COMMIT_SHA:0:7} ($(date '+%Y-%m-%d %H:%M:%S'))" -n ${K8S_NAMESPACE} --overwrite
      - kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE} --timeout=10m
      - kubectl get pods -n ${K8S_NAMESPACE} -l app=portfolio-nextjs -o wide

depends_on:
  - build
