# Release Pipeline - Build, Push, and Deploy on version tags
# Triggered on semantic version tags (v1.2.3, v2.0.0, etc.)

variables:
  K8S_NAMESPACE: portfolio
  DEPLOYMENT_NAME: portfolio-nextjs
  CONTAINER_NAME: nextjs

steps:
  # Validate Version
  validate-version:
    image: alpine:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    commands:
      - |
        VERSION=${CI_COMMIT_TAG}
        VERSION_NO_V=${VERSION#v}
        echo "Detected version: $VERSION"

        # Validate semantic version format
        if ! echo "$VERSION_NO_V" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Invalid version format: $VERSION_NO_V"
          echo "Expected format: v1.2.3 (MAJOR.MINOR.PATCH)"
          exit 1
        fi

        echo "Version format valid: $VERSION_NO_V"

  # Test
  release-test:
    image: node:20-alpine
    when:
      event: tag
      ref: refs/tags/v*.*.*
    environment:
      PNPM_HOME: /root/.pnpm
      PATH: ${PNPM_HOME}:$PATH
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -g pnpm@10
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build
    depends_on:
      - validate-version

  # Build and Push to Dockerhub
  build-and-push-dockerhub:
    image: woodpeckerci/plugin-docker-buildx:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    settings:
      repo:
        from_secret: docker_repo
      registry: docker.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - "${CI_COMMIT_TAG}"
        - latest
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    depends_on:
      - release-test

  # Build and Push to GHCR
  build-and-push-ghcr:
    image: woodpeckerci/plugin-docker-buildx:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    settings:
      repo:
        from_secret: ghcr_repo
      registry: ghcr.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - "${CI_COMMIT_TAG}"
        - latest
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    depends_on:
      - release-test

  # Deploy to Kubernetes
  deploy:
    image: alpine/k8s:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    environment:
      KUBECONFIG: /tmp/kubeconfig
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
    commands:
      - echo "${KUBECONFIG_CONTENT}" | base64 -d > /tmp/kubeconfig
      - IMAGE="ghcr.io/${GHCR_REPO}:${CI_COMMIT_TAG}"
      - echo "Deploying release: $IMAGE"
      - kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=$IMAGE -n ${K8S_NAMESPACE}
      - kubectl annotate deployment/${DEPLOYMENT_NAME} kubernetes.io/change-cause="Deploy version ${CI_COMMIT_TAG} ($(date '+%Y-%m-%d %H:%M:%S'))" -n ${K8S_NAMESPACE} --overwrite
      - kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE} --timeout=10m
      - kubectl get pods -n ${K8S_NAMESPACE} -l app=portfolio-nextjs -o wide
      - kubectl describe deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE}
    depends_on:
      - build-and-push-ghcr

  # Smoke Tests
  smoke-tests:
    image: alpine:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    commands:
      - apk add --no-cache curl
      - |
        ENDPOINT="https://portfolio.codextechnologies.org"

        # Test homepage
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT)
        if [ $HTTP_CODE -eq 200 ]; then
          echo "Homepage check passed (HTTP $HTTP_CODE)"
        else
          echo "Homepage check failed (HTTP $HTTP_CODE)"
          exit 1
        fi

        # Test health endpoint
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT/api/health)
        if [ $HTTP_CODE -eq 200 ]; then
          echo "Health check passed (HTTP $HTTP_CODE)"
        else
          echo "Health check failed (HTTP $HTTP_CODE)"
          exit 1
        fi
    depends_on:
      - deploy

  # Create Release
  create-release:
    image: alpine/git:latest
    when:
      event: tag
      ref: refs/tags/v*.*.*
    commands:
      - apk add --no-cache curl jq
      - |
        VERSION=${CI_COMMIT_TAG}
        REPO_OWNER="${CI_REPO_OWNER}"
        REPO_NAME="${CI_REPO_NAME}"

        # Get commits since last tag
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")

        if [ -z "$PREVIOUS_TAG" ]; then
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi

        # Create release on Codeberg using API
        RELEASE_DATA=$(cat <<EOF
        {
          "tag_name": "$VERSION",
          "target_commitish": "$CI_COMMIT_SHA",
          "name": "Release $VERSION",
          "body": "$COMMITS",
          "draft": false,
          "prerelease": false
        }
        EOF
        )

        curl -X POST \
          -H "Authorization: token ${CODEBERG_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "$RELEASE_DATA" \
          "https://codeberg.org/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases"
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    depends_on:
      - smoke-tests
