# Release Workflow - Creates releases on version tags
# Triggered on version tag pushes (v*.*.* format)

when:
  event: tag
  ref: refs/tags/v*.*.*

steps:
  - name: validate-version
    image: alpine:latest
    commands:
      - |
        VERSION=${CI_COMMIT_TAG}
        VERSION_NO_V=${VERSION#v}
        echo "Detected version: $VERSION"
        if ! echo "$VERSION_NO_V" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Invalid version format: $VERSION_NO_V"
          echo "Expected format: v1.2.3 (MAJOR.MINOR.PATCH)"
          exit 1
        fi
        echo "Version format valid: $VERSION_NO_V"

  - name: release-build-dockerhub
    image: woodpeckerci/plugin-docker-buildx:latest
    depends_on:
      - release-test
    settings:
      repo:
        from_secret: docker_repo
      registry: docker.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - "${CI_COMMIT_TAG}"
        - latest
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

  - name: release-create-release
    image: alpine/git:latest
    depends_on:
      - release-smoke-tests
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - apk add --no-cache curl jq
      - |
        VERSION=${CI_COMMIT_TAG}
        REPO_OWNER="${CI_REPO_OWNER}"
        REPO_NAME="${CI_REPO_NAME}"
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi
        RELEASE_DATA='{"tag_name":"'$VERSION'","target_commitish":"'$CI_COMMIT_SHA'","name":"Release '$VERSION'","body":"'$COMMITS'","draft":false,"prerelease":false}'
        curl -X POST \
          -H "Authorization: token ${CODEBERG_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "$RELEASE_DATA" \
          "https://codeberg.org/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases"
