# Release Workflow - Creates releases on version tags
# Triggered on version tag pushes (v*.*.* format)

when:
  event: tag
  ref: refs/tags/v*.*.*

steps:
  - name: validate-version
    image: alpine:latest
    commands:
      - |
        VERSION=${CI_COMMIT_TAG}
        VERSION_NO_V=${VERSION#v}
        echo "Detected version: $VERSION"
        if ! echo "$VERSION_NO_V" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Invalid version format: $VERSION_NO_V"
          echo "Expected format: v1.2.3 (MAJOR.MINOR.PATCH)"
          exit 1
        fi
        echo "Version format valid: $VERSION_NO_V"

  - name: release-test
    image: node:20-alpine
    depends_on:
      - validate-version
    environment:
      PNPM_HOME: /root/.pnpm
      PATH: ${PNPM_HOME}:$PATH
      SKIP_ENV_VALIDATION: "true"
    commands:
      - npm install -g pnpm@10
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm tsc --noEmit
      - pnpm build

  - name: release-build-dockerhub
    image: woodpeckerci/plugin-docker-buildx:latest
    depends_on:
      - release-test
    settings:
      repo:
        from_secret: docker_repo
      registry: docker.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - "${CI_COMMIT_TAG}"
        - latest
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

  - name: release-build-ghcr
    image: woodpeckerci/plugin-docker-buildx:latest
    depends_on:
      - release-test
    settings:
      repo:
        from_secret: ghcr_repo
      registry: ghcr.io
      dockerfile: Dockerfile
      platforms: linux/amd64
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - "${CI_COMMIT_TAG}"
        - latest
      build_args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

  - name: release-deploy-k8s
    image: alpine/k8s:latest
    depends_on:
      - release-build-ghcr
    environment:
      KUBECONFIG: /tmp/kubeconfig
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig_content
      GHCR_REPO:
        from_secret: ghcr_repo
    commands:
      - echo "${KUBECONFIG_CONTENT}" | base64 -d > /tmp/kubeconfig
      - IMAGE="ghcr.io/${GHCR_REPO}:${CI_COMMIT_TAG}"
      - printf "Deploying release %s\n" "$IMAGE"
      - kubectl set image deployment/portfolio-nextjs nextjs=$IMAGE -n portfolio
      - kubectl annotate deployment/portfolio-nextjs kubernetes.io/change-cause="Deploy version ${CI_COMMIT_TAG} ($(date '+%Y-%m-%d %H:%M:%S'))" -n portfolio --overwrite
      - kubectl rollout status deployment/portfolio-nextjs -n portfolio --timeout=10m
      - kubectl get pods -n portfolio -l app=portfolio-nextjs -o wide
      - kubectl describe deployment/portfolio-nextjs -n portfolio

  - name: release-smoke-tests
    image: alpine:latest
    depends_on:
      - release-deploy-k8s
    commands:
      - apk add --no-cache curl
      - |
        ENDPOINT="https://portfolio.codextechnologies.org"
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT)
        if [ $HTTP_CODE -eq 200 ]; then
          echo "Homepage check passed (HTTP $HTTP_CODE)"
        else
          echo "Homepage check failed (HTTP $HTTP_CODE)"
          exit 1
        fi
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT/api/health)
        if [ $HTTP_CODE -eq 200 ]; then
          echo "Health check passed (HTTP $HTTP_CODE)"
        else
          echo "Health check failed (HTTP $HTTP_CODE)"
          exit 1
        fi

  - name: release-create-release
    image: alpine/git:latest
    depends_on:
      - release-smoke-tests
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - apk add --no-cache curl jq
      - |
        VERSION=${CI_COMMIT_TAG}
        REPO_OWNER="${CI_REPO_OWNER}"
        REPO_NAME="${CI_REPO_NAME}"
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi
        RELEASE_DATA=$(cat <<EOFDATA
        {
          "tag_name": "$VERSION",
          "target_commitish": "$CI_COMMIT_SHA",
          "name": "Release $VERSION",
          "body": "$COMMITS",
          "draft": false,
          "prerelease": false
        }
        EOFDATA
        )
        curl -X POST \
          -H "Authorization: token ${CODEBERG_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "$RELEASE_DATA" \
          "https://codeberg.org/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases"
